=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/schema.json
{
  "$id": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "$schema": "https://json-schema.org/draft-07/schema#",
  "title": "Schema for WinGet Automation Formula",
  "type": "object",
  "required": [
    "$schema",
    "PackageIdentifier",
    "Source",
    "PostResponseScript",
    "Update",
    "AdditionalInfo",
    "PostUpgradeScript",
    "Skip"
  ],
  "properties": {
    "$schema": {
      "const": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
      "type": "string"
    },
    "PackageIdentifier": {
      "type": "string",
      "pattern": "^[^\\.\\s\\\\/:\\*\\?\"<>\\|\\x01-\\x1f]{1,32}(\\.[^\\.\\s\\\\/:\\*\\?\"<>\\|\\x01-\\x1f]{1,32}){1,7}$",
      "maxLength": 128
    },
    "Source": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "InvokeType",
          "Uri",
          "Method",
          "Headers",
          "Body",
          "UserAgent"
        ],
        "properties": {
          "InvokeType": {
            "enum": ["RestMethod", "WebRequest"],
            "type": "string"
          },
          "Uri": {
            "type": "string"
          },
          "Method": {
            "enum": [
              "Default",
              "Delete",
              "Get",
              "Head",
              "Merge",
              "Options",
              "Patch",
              "Post",
              "Put",
              "Trace"
            ],
            "type": "string"
          },
          "Headers": {
            "type": "object",
            "properties": {
              "Authorization": {
                "type": "string",
                "examples": ["\"Bearer $GithubBotToken\" #default-gh"]
              },
              "Accept": {
                "type": "string",
                "examples": ["application/vnd.github.v3+json"]
              }
            },
            "additionalProperties": { "type": "string" }
          },
          "Body": {
            "type": "string"
          },
          "UserAgent": {
            "type": "string"
          },
          "MaximumRedirection": {
            "type": "integer",
            "default": 5
          },
          "SkipHttpErrorCheck": {
            "type": "boolean",
            "default": false
          },
          "ErrorAction": {
            "type": "string",
            "enum": [
              "Break",
              "Continue",
              "Ignore",
              "Inquire",
              "SilentlyContinue",
              "Stop",
              "Suspend"
            ]
          }
        },
        "additionalProperties": false
      },
      "uniqueItems": true
    },
    "PostResponseScript": {
      "type": ["string", "array"],
      "examples": [
        "$UpdateCondition = $Response.prerelease -eq $PreRelease #default-gh",
        "$Response = $Response.BaseResponse.RequestMessage.RequestUri.OriginalString #default-headrequest",
        "$Response = $Response | ConvertFrom-Yaml",
        "$Response = [System.Text.Encoding]::UTF8.GetString($Response.RawContentStream.ToArray()) | ConvertFrom-Yaml"
      ],
      "uniqueItems": true
    },
    "Update": {
      "type": "object",
      "required": ["PackageVersion", "InstallerUrls"],
      "properties": {
        "PackageVersion": {
          "type": "string",
          "examples": [
            "$Response.tag_name.TrimStart('v') #default-gh",
            "($Response | Select-String -Pattern '(?<=v)[0-9.]+').Matches.Value #default-headrequest",
            "$Response.version"
          ]
        },
        "InstallerUrls": {
          "type": ["string", "object"],
          "patternProperties": {
            "^(x86|x64|arm|arm64|neutral)(\\|(user|machine))?$|^(user|machine)$": {
              "type": "string"
            }
          },
          "examples": [
            "$Response.assets.Where({ $_.name -match '.(exe|msi|msix|appx)(bundle){0,1}$' }).browser_download_url #default-gh",
            "$Response #default-headrequest",
            "$InstUri.Replace('#version', $Response.version)"
          ],
          "additionalProperties": false
        },
        "ProductCode": {
          "$id": "#/properties/Update/properties/ProductCode",
          "type": "string"
        },
        "ReleaseDate": {
          "type": "string",
          "default": "(Get-Date -Date $Response.published_at).ToString('yyyy-MM-dd')"
        },
        "Locales": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "Name": {
                "type": "string"
              },
              "ReleaseNotesUrl": {
                "type": "string"
              },
              "ReleaseNotes": {
                "type": "string"
              }
            },
            "additionalProperties": false
          },
          "uniqueItems": true
        },
        "AppsAndFeaturesEntries": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "DisplayName": {
                "type": "string"
              },
              "Publisher": {
                "type": "string"
              },
              "DisplayVersion": {
                "type": "string"
              },
              "ProductCode": {
                "$ref": "#/properties/Update/properties/ProductCode"
              }
            },
            "additionalProperties": false
          },
          "uniqueItems": true
        }
      },
      "additionalProperties": false
    },
    "AdditionalInfo": {
      "type": "object",
      "required": ["ForceUpgrade"],
      "properties": {
        "ForceUpgrade": {
          "type": "boolean",
          "default": false
        }
      },
      "additionalProperties": { "type": "string" }
    },
    "PostUpgradeScript": {
      "type": "string"
    },
    "Skip": {
      "type": "object",
      "required": ["Skip?", "Reason"],
      "properties": {
        "Skip?": {
          "type": "boolean",
          "default": false
        },
        "Reason": {
          "type": ["null", "string"],
          "examples": [
            "Automatically marked as stale, not updated for 2.5 years"
          ]
        }
      },
      "if": {
        "properties": {
          "Skip?": {
            "const": true
          }
        }
      },
      "then": {
        "properties": {
          "Reason": {
            "type": "string",
            "minLength": 7
          }
        }
      },
      "else": {
        "properties": {
          "Reason": {
            "type": "null"
          }
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/w/wondershare.ubackit.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "Wondershare.UBackit",
  "Source": [
    {
      "InvokeType": "RestMethod",
      "Uri": "https://cbs.wondershare.com/go.php?m=upgrade_info&pid=8767&version=1.0.0.0",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = $Response.Respone.WhatNews.FirstChild",
  "Update": {
    "InstallerUrls": "$InstUri.Replace('#version', $Response.Version)",
    "PackageVersion": "(.\\winget-pkgs-automation.exe gii --json \"$($Update.InstallerUrls)\" | ConvertFrom-Json).PackageVersion",
    "Locales": [
      {
        "Name": "en-us",
        "ReleaseNotes": "$Response.Text.'#cdata-section'"
      }
    ]
  },
  "AdditionalInfo": {
    "InstUri": "https://download.wondershare.com/cbs_down/ubackit_#version_full8767.exe",
    "ForceUpgrade": false
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/t/telerik.fiddler.everywhere.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "Telerik.Fiddler.Everywhere",
  "Source": [
    {
      "InvokeType": "WebRequest",
      "Uri": "https://api.getfiddler.com/win/latest",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = $Response.BaseResponse.RequestMessage.RequestUri.OriginalString",
  "Update": {
    "PackageVersion": "($Response | Select-String -Pattern '(?<=%20)[0-9.]+(?=\\.)').Matches.Value",
    "InstallerUrls": "$Response"
  },
  "AdditionalInfo": {
    "ForceUpgrade": false
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/p/principle.lusun.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "Principle.Lusun",
  "Source": [
    {
      "InvokeType": "RestMethod",
      "Uri": "https://releases.lusun.com/latest.yml",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = $Response | ConvertFrom-Yaml",
  "Update": {
    "PackageVersion": "$Response.version",
    "InstallerUrls": "@($x64_Uri.Replace('#version', $Response.version), $x86_Uri.Replace('#version', $Response.version))",
    "ReleaseDate": "(Get-Date -Date $Response.releaseDate).ToString('yyyy-MM-dd')",
    "Locales": [
      {
        "Name": "en-us",
        "ReleaseNotes": "$Response.releaseNotes"
      }
    ]
  },
  "AdditionalInfo": {
    "x64_Uri": "https://releases.lusun.com/lusun-#version-win-x64.exe",
    "x86_Uri": "https://releases.lusun.com/lusun-#version-win-ia32.exe",
    "ForceUpgrade": false
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/r/remnote.remnote.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "RemNote.RemNote",
  "Source": [
    {
      "InvokeType": "RestMethod",
      "Uri": "https://download.remnote.io/latest.yml",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = $Response | ConvertFrom-Yaml",
  "Update": {
    "PackageVersion": "$Response.version",
    "InstallerUrls": "'https://download.remnote.io/' + [System.Uri]::EscapeDataString($Response.path)",
    "ReleaseDate": "(Get-Date -Date $Response.releaseDate).ToString('yyyy-MM-dd')"
  },
  "AdditionalInfo": {
    "ForceUpgrade": false
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/1/1mhz.knotes.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "1MHz.Knotes",
  "Source": [
    {
      "InvokeType": "RestMethod",
      "Uri": "https://knotes2-release-cn.s3.amazonaws.com/win/latest.yml",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = $Response | ConvertFrom-Yaml",
  "Update": {
    "PackageVersion": "$Response.version",
    "InstallerUrls": "@(\"$($InstallerUrl.Replace('#path', [System.Uri]::EscapeDataString($Response.path)))|x64|user\", \"$($InstallerUrl.Replace('#path', [System.Uri]::EscapeDataString($Response.path)))|x64|machine\")",
    "ReleaseDate": "(Get-Date -Date $Response.releaseDate).ToString('yyyy-MM-dd')"
  },
  "AdditionalInfo": {
    "ForceUpgrade": false,
    "InstallerUrl": "https://knotes2-release-cn.s3.amazonaws.com/win/#path"
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/b/brave.brave.beta.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "Brave.Brave.Beta",
  "Source": [
    {
      "InvokeType": "RestMethod",
      "Uri": "https://updates.bravesoftware.com/service/update2",
      "Method": "Post",
      "Headers": {},
      "Body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?><request protocol=\"3.0\" updaterversion=\"1.3.361.133\" ismachine=\"1\" sessionid=\"{a83fa575-42a3-43cc-9534-c5db64139184}\" requestid=\"{ccfb7f34-db1b-424b-abbf-b74bcef451dc}\"><os platform=\"win\" version=\"10\" sp=\"\" arch=\"x64\" /><app appid=\"{103BD053-949B-43A8-9120-2E424887DE11}\" version=\"\" nextversion=\"\" ap=\"x86-be\" lang=\"\" brand=\"\" client=\"\"><updatecheck /></app><app appid=\"{103BD053-949B-43A8-9120-2E424887DE11}\" version=\"\" nextversion=\"\" ap=\"x64-be\" lang=\"\" brand=\"\" client=\"\"><updatecheck /></app></request>",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = $Response.response",
  "Update": {
    "PackageVersion": "$Response.app[0].updatecheck.manifest.version",
    "InstallerUrls": "@(($Response.app[1].updatecheck.urls.url.codebase + $Response.app[1].updatecheck.manifest.packages.package.name), ($Response.app[0].updatecheck.urls.url.codebase + $Response.app[0].updatecheck.manifest.packages.package.name))"
  },
  "AdditionalInfo": {
    "ForceUpgrade": false,
    "VersionRegex": "(?<=v)[0-9.]+",
    "InstallerRegex": ".(exe|msi|msix|appx)(bundle){0,1}$"
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/t/ttkn.cnkiexpress.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "TTKN.CNKIExpress",
  "Source": [
    {
      "InvokeType": "WebRequest",
      "Uri": "https://download.cnki.net/cnkiexpress/latest.yml",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = [System.Text.Encoding]::UTF8.GetString($Response.RawContentStream.ToArray()) | ConvertFrom-Yaml",
  "Update": {
    "PackageVersion": "$Response.version",
    "InstallerUrls": "\"https://download.cnki.net/cnkiexpress/$([System.Uri]::EscapeUriString($Response.path))\"",
    "ReleaseDate": "(Get-Date -Date $Response.releaseDate).ToString('yyyy-MM-dd')"
  },
  "AdditionalInfo": {
    "ForceUpgrade": false
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/a/atomixproductions.virtualdj.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "AtomixProductions.VirtualDJ",
  "Source": [
    {
      "InvokeType": "WebRequest",
      "Uri": "https://www.virtualdj.com/download/pc",
      "Method": "Head",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = $Response.BaseResponse.RequestMessage.RequestUri.OriginalString",
  "Update": {
    "PackageVersion": "(.\\winget-pkgs-automation.exe gii --json \"$($Response)\" | ConvertFrom-Json).PackageVersion",
    "InstallerUrls": "$Response"
  },
  "AdditionalInfo": {
    "ForceUpgrade": false,
    "VersionRegex": "[0-9.]+",
    "InstallerRegex": ".(exe|msi|msix|appx)(bundle){0,1}$"
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}
