=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/schema.json
{
  "$id": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "$schema": "https://json-schema.org/draft-07/schema#",
  "title": "Schema for WinGet Automation Formula",
  "type": "object",
  "required": [
    "$schema",
    "PackageIdentifier",
    "Source",
    "PostResponseScript",
    "Update",
    "AdditionalInfo",
    "PostUpgradeScript",
    "Skip"
  ],
  "properties": {
    "$schema": {
      "const": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
      "type": "string"
    },
    "PackageIdentifier": {
      "type": "string",
      "pattern": "^[^\\.\\s\\\\/:\\*\\?\"<>\\|\\x01-\\x1f]{1,32}(\\.[^\\.\\s\\\\/:\\*\\?\"<>\\|\\x01-\\x1f]{1,32}){1,7}$",
      "maxLength": 128
    },
    "Source": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "InvokeType",
          "Uri",
          "Method",
          "Headers",
          "Body",
          "UserAgent"
        ],
        "properties": {
          "InvokeType": {
            "enum": ["RestMethod", "WebRequest"],
            "type": "string"
          },
          "Uri": {
            "type": "string"
          },
          "Method": {
            "enum": [
              "Default",
              "Delete",
              "Get",
              "Head",
              "Merge",
              "Options",
              "Patch",
              "Post",
              "Put",
              "Trace"
            ],
            "type": "string"
          },
          "Headers": {
            "type": "object",
            "properties": {
              "Authorization": {
                "type": "string",
                "examples": ["\"Bearer $GithubBotToken\" #default-gh"]
              },
              "Accept": {
                "type": "string",
                "examples": ["application/vnd.github.v3+json"]
              }
            },
            "additionalProperties": { "type": "string" }
          },
          "Body": {
            "type": "string"
          },
          "UserAgent": {
            "type": "string"
          },
          "MaximumRedirection": {
            "type": "integer",
            "default": 5
          },
          "SkipHttpErrorCheck": {
            "type": "boolean",
            "default": false
          },
          "ErrorAction": {
            "type": "string",
            "enum": [
              "Break",
              "Continue",
              "Ignore",
              "Inquire",
              "SilentlyContinue",
              "Stop",
              "Suspend"
            ]
          }
        },
        "additionalProperties": false
      },
      "uniqueItems": true
    },
    "PostResponseScript": {
      "type": ["string", "array"],
      "examples": [
        "$UpdateCondition = $Response.prerelease -eq $PreRelease #default-gh",
        "$Response = $Response.BaseResponse.RequestMessage.RequestUri.OriginalString #default-headrequest",
        "$Response = $Response | ConvertFrom-Yaml",
        "$Response = [System.Text.Encoding]::UTF8.GetString($Response.RawContentStream.ToArray()) | ConvertFrom-Yaml"
      ],
      "uniqueItems": true
    },
    "Update": {
      "type": "object",
      "required": ["PackageVersion", "InstallerUrls"],
      "properties": {
        "PackageVersion": {
          "type": "string",
          "examples": [
            "$Response.tag_name.TrimStart('v') #default-gh",
            "($Response | Select-String -Pattern '(?<=v)[0-9.]+').Matches.Value #default-headrequest",
            "$Response.version"
          ]
        },
        "InstallerUrls": {
          "type": ["string", "object"],
          "patternProperties": {
            "^(x86|x64|arm|arm64|neutral)(\\|(user|machine))?$|^(user|machine)$": {
              "type": "string"
            }
          },
          "examples": [
            "$Response.assets.Where({ $_.name -match '.(exe|msi|msix|appx)(bundle){0,1}$' }).browser_download_url #default-gh",
            "$Response #default-headrequest",
            "$InstUri.Replace('#version', $Response.version)"
          ],
          "additionalProperties": false
        },
        "ProductCode": {
          "$id": "#/properties/Update/properties/ProductCode",
          "type": "string"
        },
        "ReleaseDate": {
          "type": "string",
          "default": "(Get-Date -Date $Response.published_at).ToString('yyyy-MM-dd')"
        },
        "Locales": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "Name": {
                "type": "string"
              },
              "ReleaseNotesUrl": {
                "type": "string"
              },
              "ReleaseNotes": {
                "type": "string"
              }
            },
            "additionalProperties": false
          },
          "uniqueItems": true
        },
        "AppsAndFeaturesEntries": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "DisplayName": {
                "type": "string"
              },
              "Publisher": {
                "type": "string"
              },
              "DisplayVersion": {
                "type": "string"
              },
              "ProductCode": {
                "$ref": "#/properties/Update/properties/ProductCode"
              }
            },
            "additionalProperties": false
          },
          "uniqueItems": true
        }
      },
      "additionalProperties": false
    },
    "AdditionalInfo": {
      "type": "object",
      "required": ["ForceUpgrade"],
      "properties": {
        "ForceUpgrade": {
          "type": "boolean",
          "default": false
        }
      },
      "additionalProperties": { "type": "string" }
    },
    "PostUpgradeScript": {
      "type": "string"
    },
    "Skip": {
      "type": "object",
      "required": ["Skip?", "Reason"],
      "properties": {
        "Skip?": {
          "type": "boolean",
          "default": false
        },
        "Reason": {
          "type": ["null", "string"],
          "examples": [
            "Automatically marked as stale, not updated for 2.5 years"
          ]
        }
      },
      "if": {
        "properties": {
          "Skip?": {
            "const": true
          }
        }
      },
      "then": {
        "properties": {
          "Reason": {
            "type": "string",
            "minLength": 7
          }
        }
      },
      "else": {
        "properties": {
          "Reason": {
            "type": "null"
          }
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/e/edrawsoft.mindmaster.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "EdrawSoft.MindMaster",
  "Source": [
    {
      "InvokeType": "RestMethod",
      "Uri": "https://pc-api.wondershare.cc/v2/product/check-upgrade?pid=5375&client_sign=%7B%7D&version=8.0.0&platform=win_x86",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = $Response.data",
  "Update": {
    "InstallerUrls": "$InstUri.Replace('#version', $Response.version)",
    "PackageVersion": "(.\\winget-pkgs-automation.exe gii --json \"$($Update.InstallerUrls)\" | ConvertFrom-Json).PackageVersion",
    "Locales": [
      {
        "Name": "en-us",
        "ReleaseNotes": "$Response.whats_new_content"
      }
    ]
  },
  "AdditionalInfo": {
    "InstUri": "https://cc-download.edrawsoft.cn/cbs_down/mindmaster_cn_#version_full5375.exe",
    "ForceUpgrade": false,
    "VersionRegex": "[0-9.]+",
    "InstallerRegex": ".(exe|msi|msix|appx)(bundle){0,1}$"
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/j/jinweizhiguang.mastergo.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "JinweiZhiguang.MasterGo",
  "Source": [
    {
      "InvokeType": "RestMethod",
      "Uri": "https://static-nc.mastergo.com/plugins/desktop/windows/latest.yml",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = $Response | ConvertFrom-Yaml",
  "Update": {
    "PackageVersion": "$Response.version",
    "InstallerUrls": "$InstUri.Replace('#path', $Response.path)",
    "ReleaseDate": "(Get-Date -Date $Response.releaseDate).ToString('yyyy-MM-dd')",
    "Locales": [
      {
        "Name": "en-us",
        "ReleaseNotesUrl": "'https://mastergo.com/updateRecord'"
      }
    ]
  },
  "AdditionalInfo": {
    "InstUri": "https://static.mastergo.com/plugins/desktop/windows/#path",
    "ForceUpgrade": false
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/s/splitcam.splitcam.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "SplitCam.SplitCam",
  "Source": [
    {
      "InvokeType": "WebRequest",
      "Uri": "https://splitcam.com/download",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    },
    {
      "InvokeType": "WebRequest",
      "Uri": "https://splitcam.com/win-download/update/history.txt",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response2 = $Response2.Content -split '\\n'",
  "Update": {
    "PackageVersion": "($Response.Content | Select-String -Pattern '(?<=SplitCam v)[\\d.]+(?=\\s)').Matches.Value",
    "InstallerUrls": "@($x64_Uri.Replace('#version', $UpdateInfo.PackageVersion), $x86_Uri.Replace('#version', $UpdateInfo.PackageVersion))",
    "ReleaseDate": "(Get-Date -Date $Response2[2]).ToString('yyyy-MM-dd')",
    "Locales": [
      {
        "Name": "en-US",
        "ReleaseNotesUrl": "https://splitcam.com/splitcam-changes-win"
      }
    ]
  },
  "AdditionalInfo": {
    "x64_Uri": "https://splitcam.com/win-download/update/#version_x64.msi",
    "x86_Uri": "https://splitcam.com/win-download/update/#version.msi",
    "ForceUpgrade": false
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/f/fenghe.focusnote.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "FengHe.FocusNote",
  "Source": [
    {
      "InvokeType": "RestMethod",
      "Uri": "https://fn.kirakuapp.com/admin/version/listNew",
      "Method": "Post",
      "Headers": {},
      "Body": "platform=0&prodNo=0",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = $Response.data[0].downloadUrl",
  "Update": {
    "PackageVersion": "([System.Uri]::UnescapeDataString($Response) | Select-String -Pattern $VersionRegex).Matches.Value",
    "InstallerUrls": "$Response"
  },
  "AdditionalInfo": {
    "ForceUpgrade": false,
    "VersionRegex": "[0-9.-]{2,}(?=\\.)",
    "InstallerRegex": ".exe$"
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/b/bosyun.boardmix.cn.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "Bosyun.BoardMix.CN",
  "Source": [
    {
      "InvokeType": "RestMethod",
      "Uri": "https://api.boardmix.cn/api/upgrade/desktop/bosyun/latest.yml",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = $Response | ConvertFrom-Yaml",
  "Update": {
    "PackageVersion": "$Response.version",
    "InstallerUrls": "$Response.files[0].url",
    "ReleaseDate": "(Get-Date -Date $Response.releaseDate).ToString('yyyy-MM-dd')",
    "Locales": [
      {
        "Name": "zh-CN",
        "ReleaseNotes": "$Response.releaseNotes"
      }
    ]
  },
  "AdditionalInfo": {
    "ForceUpgrade": false,
    "VersionRegex": "[0-9.]+",
    "InstallerRegex": ".(exe|msi|msix|appx)(bundle){0,1}$"
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/s/spotify.spotify.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "Spotify.Spotify",
  "Source": [
    {
      "InvokeType": "WebRequest",
      "Uri": "https://download.scdn.co/SpotifyFullSetup.exe",
      "Method": "Head",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = $Response.BaseResponse.RequestMessage.RequestUri.OriginalString",
  "Update": {
    "PackageVersion": "(.\\winget-pkgs-automation.exe gii --json \"$($Response)\" | ConvertFrom-Json).PackageVersion",
    "InstallerUrls": "$Response"
  },
  "AdditionalInfo": {
    "ForceUpgrade": false
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/t/tencent.qq.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "Tencent.QQ",
  "Source": [
    {
      "InvokeType": "WebRequest",
      "Uri": "https://im.qq.com/pcqq",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = $Response | Select-Object -Property Content, Links",
  "Update": {
    "PackageVersion": "($Response.Links.href.Where({ $_.EndsWith('.exe') }) | Select-String -Pattern '(?<=QQ)[0-9.]+(?=\\.exe)').Matches.Value",
    "InstallerUrls": "$Response.Links.href.Where({ $_.EndsWith('.exe') })",
    "ReleaseDate": "(Get-Date -Date (($Response.Content | Select-String -Pattern $ReleaseDateRegex).Matches.Value -replace '[^0-9]', '/').Trim('/')).ToString('yyyy-MM-dd')"
  },
  "AdditionalInfo": {
    "Comment": "Chinese unicode characters taken from website for regex matching",
    "ReleaseDateRegex": "(?<=\\>发布时间：).*(?=\\</span\\>)",
    "ForceUpgrade": false
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/j/jetbrains.webstorm.eap.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "JetBrains.WebStorm.EAP",
  "Source": [
    {
      "InvokeType": "RestMethod",
      "Uri": "https://data.services.jetbrains.com/products/releases?latest=true&type=eap&code=WS",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = $Response.WS",
  "Update": {
    "PackageVersion": "$Response.build",
    "InstallerUrls": "($Response.downloads.windows.link -replace \"https://download.jetbrains.com\",\"https://download-cdn.jetbrains.com\")",
    "ReleaseDate": "$Response.date",
    "ProductCode": "'WebStorm ' + $Response.build",
    "Locales": [
      {
        "Name": "en-us",
        "ReleaseNotesUrl": "$Response.notesLink"
      }
    ]
  },
  "AdditionalInfo": {
    "ForceUpgrade": false
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}
