=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/schema.json
{
  "$id": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "$schema": "https://json-schema.org/draft-07/schema#",
  "title": "Schema for WinGet Automation Formula",
  "type": "object",
  "required": [
    "$schema",
    "PackageIdentifier",
    "Source",
    "PostResponseScript",
    "Update",
    "AdditionalInfo",
    "PostUpgradeScript",
    "Skip"
  ],
  "properties": {
    "$schema": {
      "const": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
      "type": "string"
    },
    "PackageIdentifier": {
      "type": "string",
      "pattern": "^[^\\.\\s\\\\/:\\*\\?\"<>\\|\\x01-\\x1f]{1,32}(\\.[^\\.\\s\\\\/:\\*\\?\"<>\\|\\x01-\\x1f]{1,32}){1,7}$",
      "maxLength": 128
    },
    "Source": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "InvokeType",
          "Uri",
          "Method",
          "Headers",
          "Body",
          "UserAgent"
        ],
        "properties": {
          "InvokeType": {
            "enum": ["RestMethod", "WebRequest"],
            "type": "string"
          },
          "Uri": {
            "type": "string"
          },
          "Method": {
            "enum": [
              "Default",
              "Delete",
              "Get",
              "Head",
              "Merge",
              "Options",
              "Patch",
              "Post",
              "Put",
              "Trace"
            ],
            "type": "string"
          },
          "Headers": {
            "type": "object",
            "properties": {
              "Authorization": {
                "type": "string",
                "examples": ["\"Bearer $GithubBotToken\" #default-gh"]
              },
              "Accept": {
                "type": "string",
                "examples": ["application/vnd.github.v3+json"]
              }
            },
            "additionalProperties": { "type": "string" }
          },
          "Body": {
            "type": "string"
          },
          "UserAgent": {
            "type": "string"
          },
          "MaximumRedirection": {
            "type": "integer",
            "default": 5
          },
          "SkipHttpErrorCheck": {
            "type": "boolean",
            "default": false
          },
          "ErrorAction": {
            "type": "string",
            "enum": [
              "Break",
              "Continue",
              "Ignore",
              "Inquire",
              "SilentlyContinue",
              "Stop",
              "Suspend"
            ]
          }
        },
        "additionalProperties": false
      },
      "uniqueItems": true
    },
    "PostResponseScript": {
      "type": ["string", "array"],
      "examples": [
        "$UpdateCondition = $Response.prerelease -eq $PreRelease #default-gh",
        "$Response = $Response.BaseResponse.RequestMessage.RequestUri.OriginalString #default-headrequest",
        "$Response = $Response | ConvertFrom-Yaml",
        "$Response = [System.Text.Encoding]::UTF8.GetString($Response.RawContentStream.ToArray()) | ConvertFrom-Yaml"
      ],
      "uniqueItems": true
    },
    "Update": {
      "type": "object",
      "required": ["PackageVersion", "InstallerUrls"],
      "properties": {
        "PackageVersion": {
          "type": "string",
          "examples": [
            "$Response.tag_name.TrimStart('v') #default-gh",
            "($Response | Select-String -Pattern '(?<=v)[0-9.]+').Matches.Value #default-headrequest",
            "$Response.version"
          ]
        },
        "InstallerUrls": {
          "type": ["string", "object"],
          "patternProperties": {
            "^(x86|x64|arm|arm64|neutral)(\\|(user|machine))?$|^(user|machine)$": {
              "type": "string"
            }
          },
          "examples": [
            "$Response.assets.Where({ $_.name -match '.(exe|msi|msix|appx)(bundle){0,1}$' }).browser_download_url #default-gh",
            "$Response #default-headrequest",
            "$InstUri.Replace('#version', $Response.version)"
          ],
          "additionalProperties": false
        },
        "ProductCode": {
          "$id": "#/properties/Update/properties/ProductCode",
          "type": "string"
        },
        "ReleaseDate": {
          "type": "string",
          "default": "(Get-Date -Date $Response.published_at).ToString('yyyy-MM-dd')"
        },
        "Locales": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "Name": {
                "type": "string"
              },
              "ReleaseNotesUrl": {
                "type": "string"
              },
              "ReleaseNotes": {
                "type": "string"
              }
            },
            "additionalProperties": false
          },
          "uniqueItems": true
        },
        "AppsAndFeaturesEntries": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "DisplayName": {
                "type": "string"
              },
              "Publisher": {
                "type": "string"
              },
              "DisplayVersion": {
                "type": "string"
              },
              "ProductCode": {
                "$ref": "#/properties/Update/properties/ProductCode"
              }
            },
            "additionalProperties": false
          },
          "uniqueItems": true
        }
      },
      "additionalProperties": false
    },
    "AdditionalInfo": {
      "type": "object",
      "required": ["ForceUpgrade"],
      "properties": {
        "ForceUpgrade": {
          "type": "boolean",
          "default": false
        }
      },
      "additionalProperties": { "type": "string" }
    },
    "PostUpgradeScript": {
      "type": "string"
    },
    "Skip": {
      "type": "object",
      "required": ["Skip?", "Reason"],
      "properties": {
        "Skip?": {
          "type": "boolean",
          "default": false
        },
        "Reason": {
          "type": ["null", "string"],
          "examples": [
            "Automatically marked as stale, not updated for 2.5 years"
          ]
        }
      },
      "if": {
        "properties": {
          "Skip?": {
            "const": true
          }
        }
      },
      "then": {
        "properties": {
          "Reason": {
            "type": "string",
            "minLength": 7
          }
        }
      },
      "else": {
        "properties": {
          "Reason": {
            "type": "null"
          }
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/b/bytedance.jianyingpro.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "ByteDance.JianyingPro",
  "Source": [
    {
      "InvokeType": "RestMethod",
      "Uri": "https://lf3-beecdn.bytetos.com/obj/ies-fe-bee/bee_prod/biz_80/bee_prod_80_bee_publish_3563.json",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = $Response.windows_download_pkg.channel_default",
  "Update": {
    "PackageVersion": "($Response | Select-String -Pattern $VersionRegex).Matches.Value.Replace('_', '.')",
    "InstallerUrls": "$Response"
  },
  "AdditionalInfo": {
    "ForceUpgrade": false,
    "VersionRegex": "(?<=_)[0-9_]+(?=_)",
    "InstallerRegex": ".exe$"
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/a/adobe.adobeconnect.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "Adobe.AdobeConnect",
  "Source": [
    {
      "InvokeType": "WebRequest",
      "Uri": "https://www.adobe.com/go/Connect11msi",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = $Response.BaseResponse.RequestMessage.RequestUri.OriginalString",
  "Update": {
    "PackageVersion": "($Response | Select-String -Pattern $VersionRegex).Matches.Value",
    "InstallerUrls": "$Response"
  },
  "AdditionalInfo": {
    "ForceUpgrade": false,
    "VersionRegex": "[0-9.]+",
    "InstallerRegex": ".(exe|msi|msix|appx)(bundle){0,1}$"
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/o/openjs.nodejs.nightly.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "OpenJS.NodeJS.Nightly",
  "Source": [
    {
      "InvokeType": "RestMethod",
      "Uri": "https://nodejs.org/download/nightly/index.json",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": [
    "$Response = $Response[0]",
    "$UpdateCondition = $Response.version -ne $PreviousVersionRaw"
  ],
  "Update": {
    "PackageVersion": "$Response.version.TrimStart('v') -replace '-nightly.*', $Null",
    "InstallerUrls": "@($x64_Uri.Replace('#raw_version', $Response.version), $x86_Uri.Replace('#raw_version', $Response.version))",
    "ReleaseDate": "$Response.date"
  },
  "AdditionalInfo": {
    "x64_Uri": "https://nodejs.org/download/nightly/#raw_version/node-#raw_version-x64.msi",
    "x86_Uri": "https://nodejs.org/download/nightly/#raw_version/node-#raw_version-x86.msi",
    "PreviousVersionRaw": "v20.0.0-nightly2022112858b60c1393",
    "ForceUpgrade": false
  },
  "PostUpgradeScript": "$Formula.AdditionalInfo.PreviousVersionRaw = $Response.version",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/j/jetbrains.teamcity.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "JetBrains.TeamCity",
  "Source": [
    {
      "InvokeType": "RestMethod",
      "Uri": "https://data.services.jetbrains.com/products/releases?latest=true&type=release&code=TC",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": [
    "$Response = $Response.TC",
    "$UpdateCondition = $Response.build -gt $LastBuildNumber"
  ],
  "Update": {
    "PackageVersion": "$Response.version + \" (build $($Response.build))\"",
    "InstallerUrls": "($Response.downloads.windows.link -replace \"https://download.jetbrains.com\",\"https://download-cdn.jetbrains.com\") + '|x64'",
    "ReleaseDate": "$Response.date",
    "ProductCode": "JetBrains TeamCity",
    "Locales": [
      {
        "Name": "en-us",
        "ReleaseNotesUrl": "$Response.notesLink"
      }
    ]
  },
  "AdditionalInfo": {
    "LastBuildNumber": "99711",
    "ForceUpgrade": false
  },
  "PostUpgradeScript": "$Formula.AdditionalInfo.LastBuildNumber = $Response.build",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/x/ximalaya.ximalaya.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "Ximalaya.Ximalaya",
  "Source": [
    {
      "InvokeType": "RestMethod",
      "Uri": "https://pc.ximalaya.com/ximalaya-pc-updater/api/v1/update/full/latest.yml",
      "Method": "Get",
      "Headers": {
        "platform": "win32",
        "version": "0.0.0",
        "buildversion": "0",
        "uid": ""
      },
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = $Response | ConvertFrom-Yaml",
  "Update": {
    "PackageVersion": "$Response.version",
    "InstallerUrls": "(Invoke-WebRequest -Uri \"https://pc.ximalaya.com/ximalaya-pc-updater/api/v1/update/full/$($Response.path)\" -Method Head -Headers $Headers).BaseResponse.RequestMessage.RequestUri.OriginalString",
    "ReleaseDate": "(Get-Date -Date $Response.releaseDate).ToString('yyyy-MM-dd')",
    "Locales": [
      {
        "Name": "en-us",
        "ReleaseNotes": "$Response.releaseNotes"
      }
    ]
  },
  "AdditionalInfo": {
    "ForceUpgrade": false
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/t/techsmith.camtasia.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "TechSmith.Camtasia",
  "Source": [
    {
      "InvokeType": "RestMethod",
      "Uri": "https://www.techsmith.com/api/v/1/products/getallversions/11",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    },
    {
      "InvokeType": "RestMethod",
      "Uri": "\"https://www.techsmith.com/api/v/1/products/getversioninfo/$(($Response | Select-Object -First 1).VersionID)\"",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response2 = $Response2.PrimaryDownloadInformation",
  "Update": {
    "InstallerUrls": "\"https://download.techsmith.com$($Response2.RelativePath)camtasia.exe\"",
    "PackageVersion": "(.\\winget-pkgs-automation.exe gii --json \"$($Update.InstallerUrls)\" | ConvertFrom-Json).PackageVersion",
    "ReleaseDate": "(Get-Date -Date $Response2.Release).ToString('yyyy-MM-dd')"
  },
  "AdditionalInfo": {
    "ForceUpgrade": false
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/j/jetbrains.fleetlauncher.eap.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "JetBrains.FleetLauncher.EAP",
  "Source": [
    {
      "InvokeType": "RestMethod",
      "Uri": "https://data.services.jetbrains.com/products/releases?latest=true&type=eap&code=FLL",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = $Response.FLL",
  "Update": {
    "PackageVersion": "$Response.version",
    "InstallerUrls": "($Response.downloads.windows_x64.link -replace \"https://download.jetbrains.com\",\"https://download-cdn.jetbrains.com\")",
    "ReleaseDate": "$Response.date",
    "Locales": [
      {
        "Name": "en-us",
        "ReleaseNotesUrl": "$Response.notesLink"
      }
    ]
  },
  "AdditionalInfo": {
    "ForceUpgrade": false
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}

=== vedantmgoyal9/vedantmgoyal9/WinGetAutomation/Formula/1/115.115.json
{
  "$schema": "https://github.com/vedantmgoyal9/vedantmgoyal9/raw/main/WinGetAutomation/schema.json",
  "PackageIdentifier": "115.115",
  "Source": [
    {
      "InvokeType": "RestMethod",
      "Uri": "https://appversion.115.com/1/web/1.0/api/chrome",
      "Method": "Get",
      "Headers": {},
      "Body": "",
      "UserAgent": ""
    }
  ],
  "PostResponseScript": "$Response = $Response.data.window_115",
  "Update": {
    "PackageVersion": "$Response.version_code",
    "InstallerUrls": "$Response.version_url",
    "ReleaseDate": "[System.DateTimeOffset]::FromUnixTimeSeconds($Response.created_time).ToString('yyyy-MM-dd')"
  },
  "AdditionalInfo": {
    "ForceUpgrade": false
  },
  "PostUpgradeScript": "",
  "Skip": {
    "Skip?": false,
    "Reason": null
  }
}
